name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CF_PROJECT_ID: 607232

jobs:
  publish_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Zip
        run: |
          rm -rf .git .github README.md
          zip -r ${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip .
      - name: Upload Zip
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
      - name: Rollback Release
        if: failure() && steps.create_release.outputs.id != ''
        uses: author/action-rollback@stable
        with:
          id: ${{ steps.create_release.id }}
          tag: ${{ github.ref }}
      - name: "Upload to CurseForge"
        if: steps.upload_zip.outcome == 'success'
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip"
          game_endpoint: "wow"
          game_versions: "WoW Burning Crusade Classic:2.5.4"
          project_id: "$CF_PROJECT_ID"
          token: "${{ secrets.CF_API_TOKEN }}"